### ISSUE TITLE
Cant send Messages [BdCompat Powercord]

### ISSUE THREAD

**Issue by Ente-sama** [An00nymushun/DiscordFreeStickers#11] opened 2022-01-27 17:40 UTC
**Bug:**
Own messages won't be delivered if the plugin is activated

**Reproduce:**
Turn the plugin on in Powercord and send a message

**Expected behavior:**
Messages are getting delivered

**Console Log:**
```js
[BDCompat:BdApi] Error occured in `instead` callback of t

VM1088 C:\Users\CurrentUser\powercord\src\Powercord\plugins\bdCompat\modules\BDApi.js:474 TypeError: Cannot read property 'apply' of undefined
    at VM1333 C:\Users\CurrentUser\powercord\src\Powercord\plugins\bdCompat\plugins\FreeStickers.plugin.js:3805
    at instead (VM1089 C:\Users\CurrentUser\powercord\src\Powercord\plugins\bdCompat\modules\Patcher.js:74)
    at VM1088 C:\Users\CurrentUser\powercord\src\Powercord\plugins\bdCompat\modules\BDApi.js:45
    at t.what.<computed> [as enqueue] (VM1088 C:\Users\CurrentUser\powercord\src\Powercord\plugins\bdCompat\modules\BDApi.js:342)
 ```

**Client:**
Discord Canary (Powercord 12de9dc),
BdCompat version v22.1.14b,
Plugin version 1.2

**Comment by An00nymushun** [comment] 2022-01-27 18:48
Duplicate of https://github.com/An00nymushun/DiscordFreeStickers/issues/9

**Closed by An00nymushun** 2022-01-27 18:48 UTC
